# Generated by Django 5.2.1 on 2025-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название фрукта', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Опишите сорт и особенности', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за 1 кг в рублях', max_digits=6, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Фрукт',
                'verbose_name_plural': 'Фрукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
